version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to AWS ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Logging in to Docker Hub..."
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing Docker image to AWS ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo "Pushing Docker image to Docker Hub..."
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG $DOCKER_USERNAME/$DOCKER_REPO_NAME:$IMAGE_TAG
      - docker push $DOCKER_USERNAME/$DOCKER_REPO_NAME:$IMAGE_TAG

env:
  variables:
    AWS_REGION: "us-east-1"  # Change this to your AWS region
    ECR_REPO_NAME: "flexibuckets"  # Replace with your ECR repository name
    IMAGE_TAG: "latest"  # Use "latest" or dynamically generated tags
    AWS_ACCOUNT_ID: "920373029788"  # Replace with your AWS Account ID
    DOCKER_USERNAME: "flexibuckets"  # Docker Hub username
    DOCKER_PASSWORD: ${{ secrets.dockerhub.DOCKERHUB_TOKEN }}  # Docker Hub access token
    DOCKER_REPO_NAME: "flexibuckets"  # Replace with your Docker Hub repository name
