export const supportedCountryCodes = [
  "DK",
  "NZ",
  "BR",
  "IN",
  "LT",
  "GR",
  "MY",
  "LU",
  "EE",
  "HU",
  "JP",
  "TH",
  "SE",
  "NO",
  "NG",
  "SG",
  "CN",
  "FR",
  "HR",
  "NL",
  "ID",
  "FI",
  "US",
  "BE",
  "DE",
  "GB",
  "AT",
  "IE",
  "HK",
  "ME",
  "CZ",
  "CH",
  "PH",
  "AU",
  "RS",
  "ES",
  "LV",
  "EG",
  "PL",
  "IT",
  "IS",
  "RO",
  "BA",
  "BD",
];

interface CountryData {
  name: string;
  code: string;
  callingCode: string;
  required_address_information: string[];
}

export const supportedCountries: CountryData[] = [
  {
    name: "Australia",
    code: "AU",
    callingCode: "+61",
    required_address_information: ["ZIP/postal code"],
  },
  {
    name: "Austria",
    code: "AT",
    callingCode: "+43",
    required_address_information: [],
  },
  {
    name: "Bangladesh",
    code: "BD",
    callingCode: "+880",
    required_address_information: [],
  },
  {
    name: "Belgium",
    code: "BE",
    callingCode: "+32",
    required_address_information: [],
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    callingCode: "+387",
    required_address_information: [],
  },
  {
    name: "Brazil",
    code: "BR",
    callingCode: "+55",
    required_address_information: [],
  },
  {
    name: "China",
    code: "CN",
    callingCode: "+86",
    required_address_information: [],
  },
  {
    name: "Croatia",
    code: "HR",
    callingCode: "+385",
    required_address_information: [],
  },
  {
    name: "Czechia (Czech Republic)",
    code: "CZ",
    callingCode: "+420",
    required_address_information: [],
  },
  {
    name: "Denmark",
    code: "DK",
    callingCode: "+45",
    required_address_information: [],
  },
  {
    name: "Egypt",
    code: "EG",
    callingCode: "+20",
    required_address_information: [],
  },
  {
    name: "Estonia",
    code: "EE",
    callingCode: "+372",
    required_address_information: [],
  },
  {
    name: "Finland",
    code: "FI",
    callingCode: "+358",
    required_address_information: [],
  },
  {
    name: "France",
    code: "FR",
    callingCode: "+33",
    required_address_information: ["ZIP/postal code"],
  },
  {
    name: "Germany",
    code: "DE",
    callingCode: "+49",
    required_address_information: ["ZIP/postal code"],
  },
  {
    name: "Greece",
    code: "GR",
    callingCode: "+30",
    required_address_information: [],
  },
  {
    name: "Hong Kong",
    code: "HK",
    callingCode: "+852",
    required_address_information: [],
  },
  {
    name: "Hungary",
    code: "HU",
    callingCode: "+36",
    required_address_information: [],
  },
  {
    name: "Iceland",
    code: "IS",
    callingCode: "+354",
    required_address_information: [],
  },
  {
    name: "India",
    code: "IN",
    callingCode: "+91",
    required_address_information: [],
  },
  {
    name: "Indonesia",
    code: "ID",
    callingCode: "+62",
    required_address_information: [],
  },
  {
    name: "Ireland",
    code: "IE",
    callingCode: "+353",
    required_address_information: [],
  },
  {
    name: "Italy",
    code: "IT",
    callingCode: "+39",
    required_address_information: [],
  },
  {
    name: "Japan",
    code: "JP",
    callingCode: "+81",
    required_address_information: [],
  },
  {
    name: "Latvia",
    code: "LV",
    callingCode: "+371",
    required_address_information: [],
  },
  {
    name: "Lithuania",
    code: "LT",
    callingCode: "+370",
    required_address_information: [],
  },
  {
    name: "Luxembourg",
    code: "LU",
    callingCode: "+352",
    required_address_information: [],
  },
  {
    name: "Malaysia",
    code: "MY",
    callingCode: "+60",
    required_address_information: [],
  },
  {
    name: "Montenegro",
    code: "ME",
    callingCode: "+382",
    required_address_information: [],
  },
  {
    name: "Netherlands",
    code: "NL",
    callingCode: "+31",
    required_address_information: [],
  },
  {
    name: "New Zealand",
    code: "NZ",
    callingCode: "+64",
    required_address_information: [],
  },
  {
    name: "Nigeria",
    code: "NG",
    callingCode: "+234",
    required_address_information: [],
  },
  {
    name: "Norway",
    code: "NO",
    callingCode: "+47",
    required_address_information: [],
  },
  {
    name: "Philippines",
    code: "PH",
    callingCode: "+63",
    required_address_information: [],
  },
  {
    name: "Poland",
    code: "PL",
    callingCode: "+48",
    required_address_information: [],
  },
  {
    name: "Romania",
    code: "RO",
    callingCode: "+40",
    required_address_information: [],
  },
  {
    name: "Serbia",
    code: "RS",
    callingCode: "+381",
    required_address_information: [],
  },
  {
    name: "Singapore",
    code: "SG",
    callingCode: "+65",
    required_address_information: [],
  },
  {
    name: "Spain",
    code: "ES",
    callingCode: "+34",
    required_address_information: [],
  },
  {
    name: "Sweden",
    code: "SE",
    callingCode: "+46",
    required_address_information: [],
  },
  {
    name: "Switzerland",
    code: "CH",
    callingCode: "+41",
    required_address_information: [],
  },
  {
    name: "Thailand",
    code: "TH",
    callingCode: "+66",
    required_address_information: [],
  },
  {
    name: "United Kingdom",
    code: "GB",
    callingCode: "+44",
    required_address_information: [],
  },
  {
    name: "United States",
    code: "US",
    callingCode: "+1",
    required_address_information: ["ZIP/postal code"],
  },
];

export const getCallingCode = (countryCode: string) => {
  const country = supportedCountries.find((c) => c.code === countryCode);
  console.log(countryCode, country);

  return country?.callingCode;
};
