name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short=6 HEAD)" >> $GITHUB_ENV
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: flexibuckets/flexibuckets:${{ env.sha_short }}
          dockerfile: Dockerfile
          context: .
          platforms: linux/amd64
          cache-from: type=local,src=.docker_cache
          cache-to: type=local,dest=.docker_cache
