name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short=6 HEAD)" >> $GITHUB_ENV

      - name: Check for changes in Dockerfile or src
        id: changes_check
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q -E '(Dockerfile|^src/)'; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push if changes detected
        if: env.changes == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
          flexibuckets/flexibuckets:${{ env.sha_short }}
          flexibuckets/flexibuckets:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update tag to latest if no changes detected
        if: env.changes == 'false'
        run: |
          echo "No significant changes detected. Updating tag to 'latest'."
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: flexibuckets/flexibuckets:latest
