name: Build and Push No-Traefik Docker Image

on:
  push:
    branches:
      - remove-traefik

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code with shallow clone
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2. Get short SHA for tagging
      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short=6 HEAD)" >> $GITHUB_ENV

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build and Push Docker image with caching
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.no-traefik
          push: true
          tags: |
            flexibuckets/flexibuckets:${{ env.sha_short }}-no-traefik
            flexibuckets/flexibuckets:no-traefik
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max 