name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get short SHA and version
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short=6 HEAD)" >> $GITHUB_ENV
          echo "version=$(cat version.txt)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            flexibuckets/flexibuckets:${{ env.sha_short }}
            flexibuckets/flexibuckets:${{ env.version }}
            flexibuckets/flexibuckets:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update version.txt
        run: |
          echo "${{ env.version }}" > version.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.txt
          git commit -m "Bump version to ${{ env.version }}"
          git push

