name: Deploy to CDN

on:
  push:
    branches:
      - main
    paths:
      - 'install.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CF_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          aws-region: auto
          endpoint-url: https://<account-id>.r2.cloudflarestorage.com

      - name: Upload to R2
        run: |
          aws s3 cp install.sh s3://${{ secrets.CF_BUCKET_NAME }}/install.sh \
            --content-type "text/x-shellscript" \
            --cache-control "public, max-age=3600" \
            --acl public-read