name: Deploy to CDN

on:
  push:
    branches:
      - main
    paths:
      - 'install.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload to R2
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.CF_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          aws s3 cp install.sh s3://${{ secrets.CF_BUCKET_NAME }}/install.sh \
            --endpoint-url https://${{ secrets.CF_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            --content-type "text/x-shellscript" \
            --cache-control "public, max-age=3600" \
            --acl public-read \
            --no-sign-request