name: Deploy to CDN

on:
  push:
    branches:
      - main
    paths:
      - 'install.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload to R2
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          BUCKET_NAME: ${{ secrets.CF_BUCKET_NAME }}
        run: |
          echo "Starting upload to R2..."
          
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/r2/buckets/${BUCKET_NAME}/objects/install.sh" \
            -H "Authorization: Bearer ${CF_API_TOKEN}" \
            -H "Content-Type: text/x-shellscript" \
            -H "Cache-Control: public, max-age=3600" \
            --data-binary "@install.sh" \
            --fail