name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code with shallow clone
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image (without pushing)
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: flexibuckets/flexibuckets:pr-check
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 4. Install Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # 5. Install dependencies
      - name: Install dependencies
        run: bun install

      # 6. Run linting
      - name: Run lint check
        run: bun run lint

      # 7. Run build check
      - name: Run build check
        run: bun run build